# Setup
title:        Project ICARUS
tagline:      Final Year Engineering Project
subtitle:     42 Stereo-Vision-Based Joint Tracking & Exercise Recognition
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Farmehr Farhoour
  url:        https://github.com/ffarhour/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
