# Setup
title:        Project ICARUS
tagline:      Final Year Engineering Project
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Farmehr Farhoour
  url:        http://projecticarus.tech/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
