# Setup
title:        Project ICARUS
tagline:      Final Year Engineering Project
baseurl:      "/Project-ICARUS"
paginate:     1

# About/contact
author:
  name:       Farmehr Farhoour
  url:        http://ffmade.me/Project-ICARUS/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
